# Generated by Django 5.0.7 on 2024-07-24 16:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_profile_phone_number_profile_birthday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='availity_id',
            field=models.CharField(blank=True, help_text="Enter the user's created Availity ID.", max_length=50, null=True, verbose_name='Availity ID'),
        ),
        migrations.AddField(
            model_name='profile',
            name='campus_key',
            field=models.CharField(blank=True, help_text="Enter the user's Jefferson/Einstein campus key.", max_length=50, null=True, verbose_name='Campus Key'),
        ),
        migrations.AddField(
            model_name='profile',
            name='modified_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='uhc_id',
            field=models.CharField(blank=True, help_text="Enter the user's United Healthcare username.", max_length=50, null=True, verbose_name='United Healthcare Username'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ip_address',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='IP field must match the following convention: 111.111.111.111', regex='^\\d{3}\\.\\d{3}\\.\\d{3}\\.\\d{3}$')], verbose_name='IP Address'),
        ),
    ]
