# Generated by Django 5.0.7 on 2024-07-24 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_profile_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='trinity_id',
            field=models.CharField(blank=True, help_text="Enter the user's Trinity Network ID.", max_length=50, null=True, verbose_name='Trinity ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='uhc_id',
            field=models.CharField(blank=True, help_text="Enter the user's United Healthcare username.", max_length=50, null=True, verbose_name='United Healthcare ID'),
        ),
    ]
