# Generated by Django 5.0.7 on 2024-07-24 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_profile_trinity_id_alter_profile_uhc_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bonus_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter bonus rate as format "0.03".', max_digits=3, null=True, verbose_name='Bonus Rate'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Analyst', 'Analyst'), ('Compliance', 'Compliance'), ('Information Technology', 'Information Technology'), ('Marketing', 'Marketing')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='offer_date',
            field=models.DateField(blank=True, help_text='Enter the date the offer letter was sent.', null=True, verbose_name='Offer Date'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='start_date',
            field=models.DateField(blank=True, help_text='Enter the date the user started.', null=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='term_date',
            field=models.DateField(blank=True, help_text="Enter the date the user's employment was terminated.", null=True, verbose_name='Term Date'),
        ),
    ]
