# Generated by Django 5.0.7 on 2024-07-24 12:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_profile_bonus_rate_alter_profile_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bonus_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter bonus rate as format "0.03".', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(limit_value=0, message='Bonus rate must be a positive number.'), django.core.validators.MaxValueValidator(limit_value=1, message='Bonus rate must not exceed 1.0 (100%)')], verbose_name='Bonus Rate'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
