# Generated by Django 5.0.7 on 2024-07-24 14:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_profile_bonus_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(blank=True, max_length=75, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='bonus_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter bonus rate as format "0.03" to represent 3%. This is the default rate for analysts.', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(limit_value=0, message='Bonus rate must be a positive number.'), django.core.validators.MaxValueValidator(limit_value=1, message='Bonus rate must not exceed 1.0')], verbose_name='Bonus Rate'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ip_address',
            field=models.CharField(blank=True, help_text="Enter the user's IP address. Use format 111.111.111.111", max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='IP field must match the following format: 111.111.111.111', regex='^\\d{3}\\.\\d{3}\\.\\d{3}\\.\\d{3}$')], verbose_name='IP Address'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(blank=True, default='TX', error_messages="Enter the state's abbreviated name.", max_length=2, null=True),
        ),
    ]
