# Generated by Django 5.0.7 on 2024-07-24 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_clientaccount_alter_profile_bonus_rate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientaccount',
            options={'verbose_name_plural': 'Client Accounts'},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='availity_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='campus_key',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='trinity_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='uhc_id',
        ),
        migrations.CreateModel(
            name='AccessCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availity_id', models.CharField(blank=True, help_text="Enter the user's created Availity ID.", max_length=50, null=True, verbose_name='Availity ID')),
                ('uhc_id', models.CharField(blank=True, help_text="Enter the user's United Healthcare username.", max_length=50, null=True, verbose_name='United Healthcare ID')),
                ('jefferson_campus_key', models.CharField(blank=True, help_text="Enter the user's Jefferson/Einstein campus key.", max_length=50, null=True, verbose_name='Campus Key')),
                ('trinity_id', models.CharField(blank=True, help_text="Enter the user's Trinity Network ID.", max_length=50, null=True, verbose_name='Trinity ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auth_access',
            },
        ),
    ]
