# Generated by Django 5.0.7 on 2024-08-12 12:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_clientaccount_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accesscredential',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='accesscredential',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Please enter the mobile phone number in the following format: 999-999-9999.', regex='^\\d{3}-\\d{3}-\\d{4}$')], verbose_name='Mobile Phone'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='office_phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Please enter the office phone number in the following format: 999-999-9999.', regex='^\\d{3}-\\d{3}-\\d{4}$')], verbose_name='Office Phone'),
        ),
    ]
