# Generated by Django 5.0.7 on 2024-08-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_film_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='film_photos/'),
        ),
    ]
